project:
  type: book
  output-dir: _book

book:
  title: Practicals
  chapters:
    - index.qmd
    - Practical One.qmd
    - Prac2.qmd
    - PracticalDay4.qmd
  sidebar:
    border: true
    background: light
    position: right
  navbar:
    search: true
    background: light

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    toc-location: left
    



