project:
  type: book
  title: Practical One
  output-dir: _site
  


book:
  chapters:
    - Practical One.qmd
    

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    toc-location: left



