project:
  type: book
  
  output-dir: docs

book:
  title: Practicals
  chapters:
    - index.qmd
    - Practical One.qmd
    - Prac2.qmd
    - PracticalDay4.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-location: left
    



